name: runner-java

env:
  path: services/runners/java
  registry: registry.digitalocean.com
  image: alessandromazzoli/squidcode-runner-java
  platforms: linux/amd64,linux/arm64

on:
  push:
    paths:
      - 'services/runners/java/**'

jobs:
  build:
    name: Build & push docker image
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v6

      - name: setup-doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: setup-doctl-registry
        run: doctl registry login --expiry-seconds 1200
      
      - name: setup-qemu
        uses: docker/setup-qemu-action@v3

      - name: setup-buildx
        uses: docker/setup-buildx-action@v3

      - name: build-and-push
        uses: docker/build-push-action@v6
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          context: ${{ env.path }}
          platforms: ${{ env.platforms }}
          push: true
          tags: ${{ env.registry }}/${{ env.image }}:latest